### ISSUE TITLE
Adding footer 

### ISSUE THREAD

**Issue by SachinMittal1766** [ghulamyazdani/TruHealth#18]
We can add a footer on the webpage containing team details Etc. I want to work on it. Please assign it to me @ghulamyazdani

**Comment by ghulamyazdani** [comment]
Great idea @SachinMittal1766  Go ahead!

**Comment by mandiraghosh783** [comment]
hello. I would love to add a footer to the web page. 
It will contain the following:
copyright
go to top
and a brief description..
can i do??

**Comment by mandiraghosh783** [comment]
please assign me

**Comment by ghulamyazdani** [comment]
@mandiraghosh783  ,@SachinMittal1766 is already working on this issue

**Comment by mandiraghosh783** [comment]
@ghulamyazdani  working on an issue which is assigned to someone else isnt allowed?
