### ISSUE TITLE
Can I add contribution guidelines

### ISSUE THREAD

**Issue by Ayan-thecodeking** [ghulamyazdani/TruHealth#2]

**Comment by ghulamyazdani** [comment]
Yeah sure @Ayan-thecodeking Go ahead!!!

**Comment by ghulamyazdani** [comment]
Yeah sure @Ayan-thecodeking Go ahead!!!

**Comment by Ayan-thecodeking** [comment]
> Yeah sure @Ayan-thecodeking Go ahead!!!

yup

**Comment by Ayan-thecodeking** [comment]
> > Yeah sure @Ayan-thecodeking Go ahead!!!
> 
> yup



> Yeah sure @Ayan-thecodeking Go ahead!!!

can you give a brief about project so that i can add about too @ghulamyazdani

**Comment by ghulamyazdani** [comment]
@Ayan-thecodeking you can take refrence from the resources given below!
#### Resources 🧾 
- [Figma Link](https://www.figma.com/file/ffaR99qwXVsQBJQL7gjlZA/TruHealth?node-id=0%3A1)
- [Documentation Link](https://docs.google.com/document/d/1g_S4Vlf6fgDXb0Esvq5mP_6whN0C9sHi0znJAQ9_Fxg/edit?usp=sharing)
- [Presentation](https://docs.google.com/document/d/1g_S4Vlf6fgDXb0Esvq5mP_6whN0C9sHi0znJAQ9_Fxg/edit?usp=sharing)
