### ISSUE TITLE
background image resizing issue

### ISSUE THREAD

**Issue by snahashisk** [ghulamyazdani/TruHealth#22]
As i am resizing the tab size bg image getting shrinked and it's messing up UI. I would like to work on this issue.
![issue-1](https://user-images.githubusercontent.com/77480125/144853206-5b6cd1ff-f148-4c6e-8039-e04589216f78.JPG)
background visible only for half of the page.
![fix1](https://user-images.githubusercontent.com/77480125/144853380-df2a8254-008b-4b23-bd04-bf75fa9418e8.JPG)
I have worked little on this now it's looking like this. I would like to work on this bit more and make all background responsive and snappy. please assign me for this.

**Comment by ghulamyazdani** [comment]
Sure @snahashisk Go ahead and make a PR for the same ,and tell me if you need any assistance in this.
