### ISSUE TITLE
fixing the position of music player

### ISSUE THREAD

**Issue by snahashisk** [ghulamyazdani/TruHealth#25]
![issue_2](https://user-images.githubusercontent.com/77480125/144878728-8425a7a6-f178-4fa1-9cf6-3d08584ec245.JPG)

**Firstly it was sticking with the above section**

![fix_2](https://user-images.githubusercontent.com/77480125/144879114-3886f2f6-ba98-4c98-a32c-5e028e6a6238.JPG)

I have fixed it and added a slight border radius I think it's looking great. Please assign me this.

**Comment by ghulamyazdani** [comment]
Sure @snahashisk go ahead!
