### ISSUE TITLE
Fixing the white space which appears when the user scrolls every page

### ISSUE THREAD

**Issue by KiZaRu507** [ghulamyazdani/TruHealth#26]
When any user scrolls to read any article on the page the green color does not appear but  white space is there in the bottom

**Comment by ghulamyazdani** [comment]
Yeah @KiZaRu507 go ahead and fix that issue and make sure to add a screenshot to give reference in an issue you create

**Comment by KiZaRu507** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/74707528/146169839-594a9bb5-1247-4b2e-844c-1833f2595b7f.png)
![Screenshot (9)](https://user-images.githubusercontent.com/74707528/146169861-b66af42f-1fdc-4767-8dd8-a9fe07dfe664.png)
![Screenshot (10)](https://user-images.githubusercontent.com/74707528/146169865-cfd4155f-7c95-4c06-90aa-cd86135a3575.png)
White spaces disrupting the look of the website
