### ISSUE TITLE
Make the links easier to find (make them more prominent)

### ISSUE THREAD

**Issue by vaibhavaaditya** [ghulamyazdani/TruHealth#29]
![image](https://user-images.githubusercontent.com/60606630/145023529-8448df1b-1a30-4826-87c0-996083bd0a33.png)

it is difficult to identify that the list of titles actually point to a video, hence i would like to make change so that when user hovers over the link, it changes colour, making it easier to identify that it is a clickable link.

**Comment by vaibhavaaditya** [comment]
@ghulamyazdani can you assign me this issue?

**Comment by ghulamyazdani** [comment]
Sure @vaibhavaaditya Go ahead and fix this one!
