### ISSUE TITLE
Responsive Navbar

### ISSUE THREAD

**Issue by anubhav201241** [ghulamyazdani/TruHealth#3]
Hey, I want to contribute to your repository, 
I want to make the website navbar responsive, can you assign this issue to me !!

**Comment by ghulamyazdani** [comment]
Sure @anubhav201241 , that would be great!  
#### Resources 🧾 
- [Figma Link](https://www.figma.com/file/ffaR99qwXVsQBJQL7gjlZA/TruHealth?node-id=0%3A1)
- [Doc Link](https://docs.google.com/document/d/1g_S4Vlf6fgDXb0Esvq5mP_6whN0C9sHi0znJAQ9_Fxg/edit?usp=sharing)
- [Presentation](https://docs.google.com/document/d/1g_S4Vlf6fgDXb0Esvq5mP_6whN0C9sHi0znJAQ9_Fxg/edit?usp=sharing)

**Comment by AKSHATNEMA** [comment]
I want to work on this issue. Please assign me this issue.

**Comment by ghulamyazdani** [comment]
Yes sure @AKSHATNEMA go ahead!!
