### ISSUE TITLE
Increase the opacity of the text background to make text easily readable 

### ISSUE THREAD

**Issue by vaibhavaaditya** [ghulamyazdani/TruHealth#30]
![image](https://user-images.githubusercontent.com/60606630/145028805-fe1b9a69-0076-42df-9f10-3398f7daed24.png)

The image background is somewhat interfering with the text due to slightly lower opacity, i would like to increase the opacity and make it easily readable. After change it would look like the following image:

![image](https://user-images.githubusercontent.com/60606630/145028682-ba770b77-f221-49d8-a344-3ea4b4e3af76.png)

**Comment by vaibhavaaditya** [comment]
@ghulamyazdani can you assign me this issue?

**Comment by ghulamyazdani** [comment]
Sharp eyes 👀 @vaibhavaaditya ,thanks for noticing it ,Surely you can work on this issue!
