### ISSUE TITLE
Incomplete point in the Info page

### ISSUE THREAD

**Issue by Raghav-goku-18** [ghulamyazdani/TruHealth#35]
The meditation point is incomplete. 
![incomplete line1](https://user-images.githubusercontent.com/95613232/145162530-8214ed6c-996a-4c12-ab54-3171f8420af9.png)

I have made an edit for the same.
![edited line](https://user-images.githubusercontent.com/95613232/145162196-749d98a2-e665-452b-ac44-1e93d28d7cc9.png)
If you like the change, please assign me on it.

**Comment by ghulamyazdani** [comment]
We have some videos there arent you able to see?

**Comment by ghulamyazdani** [comment]
![image](https://user-images.githubusercontent.com/55938346/145338136-717a5266-638c-486e-a8ba-98c59fdb9e5a.png)

**Comment by Raghav-goku-18** [comment]
I can see them but like these recommendations focus on mental health as a whole,don't they? The last line although points to something related to only meditation.
