### ISSUE TITLE
Fix the Quiz Section

### ISSUE THREAD

**Issue by snahashisk** [ghulamyazdani/TruHealth#36]
![quiz_issue_01](https://user-images.githubusercontent.com/77480125/145178462-7cbe7bc2-97e9-46bd-8ea0-628b0b427ce9.JPG)

You can select **multiple options** at a time in the quiz. Actually, you can select **all of them** if you want.

![quiz_issue_02](https://user-images.githubusercontent.com/77480125/145178726-5fa8eda9-d510-4174-b7c3-aa57b5cc4325.JPG)

If you select all of them ya more than one in select genres question the music tab will **not be generated**.

**Comment by snahashisk** [comment]
please assign me this I would like to work on this. I have already come up with a solution.

**Comment by ghulamyazdani** [comment]
Cool, @snahashisk Go ahead!
