### ISSUE TITLE
fix: Navigation Links area

### ISSUE THREAD

**Issue by Keshraf** [ghulamyazdani/TruHealth#38]
Problem:
- The anchor tag only envelops the words in the navigation bar
- Results to small click area

Solution - 
- Envelop the anchor tags around the buttons

Please assign this issue to me! 😊

**Comment by Keshraf** [comment]
I would also like to commit a change where there is space in 'Get Help'

**Comment by ghulamyazdani** [comment]
Sharp eyes 👀 ,Go ahead and make a PR /1

**Comment by Keshraf** [comment]
Thank you @ghulamyazdani . You can see the PR here #45
