### ISSUE TITLE
fix: Grammatical and Punctuational errors in the Home Page

### ISSUE THREAD

**Issue by Keshraf** [ghulamyazdani/TruHealth#39]
I checked the paragraph on Grammarly, which displayed a lot of errors.

Fixed Paragraph:

> Due to the prolonged pandemic, people are increasingly feeling isolated, which is likely to worsen their mental health. We feel like everything is just messed up, and we can’t do anything about it, and this feeling brings depression and mental illness. This website will be having information about how to deal with depression and how to keep good mental health. Experts say music really helps people who are going through any mental health issues, so taking that in mind, we have added a quiz that detects your mood and play songs, respectively. To boost morale/motivation, I have added motivational thoughts as well.

I would like to fix this error. Please assign me the issue. 😊

**Comment by ghulamyazdani** [comment]
you are Good to go!
