### ISSUE TITLE
fix: Navbar-scroll-feature-remove

### ISSUE THREAD

**Issue by Keshraf** [ghulamyazdani/TruHealth#40]
Hello,
The feature where the navigation bar disappears on the scroll is not useful.
Reasons:
- The navbar stays on the top and doesn't affect other content on the page so no point in removing it
- The vanished navbar affects the user  negatively while they are exploring the info page

![image](https://user-images.githubusercontent.com/82109991/145276176-282b85f9-0bf7-43d4-a529-ceda401eb9df.png)

As you can see here that the navbar has disappeared just by scrolling a little bit.
This would decrease user experience.

I would like to remove this feature.

Please assign this issue to me. 😊

**Comment by ghulamyazdani** [comment]
I was actually thinking about it, Go ahead and create a PR
