### ISSUE TITLE
Added Google Fonts

### ISSUE THREAD

**Issue by mandiraghosh783** [ghulamyazdani/TruHealth#43]
I have added a google font (poppins) to make it look more attractive and cleaner.
<img width="1440" alt="Screenshot 2021-12-09 at 9 05 27 AM" src="https://user-images.githubusercontent.com/92217453/145330149-866c525c-3d8a-4ead-a22a-76be68757650.png">

**Comment by ghulamyazdani** [comment]
Cool, it looks awesome, Go ahead and make a PR!
