### ISSUE TITLE
Add Project details in Readme.md

### ISSUE THREAD

**Issue by JOS-RE** [ghulamyazdani/TruHealth#5]
I wanted to contribute to this repository by making a readme for it.
Can you please assign this issue to me.

**Comment by ghulamyazdani** [comment]
Sure @JOS-RE , go ahead!
#### Resources 🧾 
- [Figma Link](https://www.figma.com/file/ffaR99qwXVsQBJQL7gjlZA/TruHealth?node-id=0%3A1)
- [Doc Link](https://docs.google.com/document/d/1g_S4Vlf6fgDXb0Esvq5mP_6whN0C9sHi0znJAQ9_Fxg/edit?usp=sharing)
- [Presentation](https://docs.google.com/document/d/1g_S4Vlf6fgDXb0Esvq5mP_6whN0C9sHi0znJAQ9_Fxg/edit?usp=sharing)
