### ISSUE TITLE
Video section looks odd

### ISSUE THREAD

**Issue by arpita221b** [ghulamyazdani/TruHealth#51]
The Video section on the info page looks a  bit odd.

![Screenshot (1199)](https://user-images.githubusercontent.com/56889637/145369828-b7e2b15a-3a7f-4c62-8b03-1a1f137e6fbb.png)

Hey, I would like to fix this issue. Can you please assign this to me?

**Comment by ghulamyazdani** [comment]
Yes @arpita221b  go ahead and fix it!
