### ISSUE TITLE
adding some stress busting browser games

### ISSUE THREAD

**Issue by snahashisk** [ghulamyazdani/TruHealth#54]
Will be adding **sudoku** and **mind game**. Adding a separate page only for games. I'll upload a few Figma designs here. Please assign me this.

**Comment by ghulamyazdani** [comment]
Perfect idea 💡 !! I would be happy to help in this if you need any help

**Comment by aryanpandey1507** [comment]
plz assign this to me i would also like to work upon this

**Comment by aryanpandey1507** [comment]
we can have some section for jokes and fun in which we can fetch some fun jokes using api

**Comment by snahashisk** [comment]
I am almost done with this issue. Assigning multiple people on the same issue will create merge conflicts. @aryanpandey1507 you can create a separate issue for the jokes and ask mentor to assign that to you.  Ig this will be better.

**Comment by snahashisk** [comment]
![game_menu](https://user-images.githubusercontent.com/77480125/145707737-79773f8d-fd96-4561-97de-4b0c707eb9fe.JPG)

I have been working on adding so many things to it like a complete change in design aspects. Giving it a **neumorphic** touch. Here is a preview.

**Comment by aryanpandey1507** [comment]
> I am almost done with this issue. Assigning multiple people on the same issue will create merge conflicts. @aryanpandey1507 you can create a separate issue for the jokes and ask mentor to assign that to you. Ig this will be better.

Ok , sorry for the confusion

**Comment by snahashisk** [comment]
@aryanpandey1507 no issue. Thank you for understanding. I would suggest you to create a separate issue. Before that discuss with the mentor.
