### ISSUE TITLE
Improve Heading Font

### ISSUE THREAD

**Issue by Keshraf** [ghulamyazdani/TruHealth#55]
Hey @ghulamyazdani,
Having the same font for all the text doesn't distinguish the heading from the content.

We can use a different font for Headings.

Suggested fonts:
- [Bebas Nueue](https://fonts.google.com/specimen/Bebas+Neue?query=beba)
- [Tinos](https://fonts.google.com/specimen/Tinos?thickness=7)
- [Raleway](https://fonts.google.com/specimen/Raleway?query=ralew)

You can choose one or suggest the one which you like.

**Comment by Keshraf** [comment]
Forgot to mention.

Please assign this issue to me 😊

**Comment by ghulamyazdani** [comment]
Yep go ahead
