### ISSUE TITLE
Adding Joke and Fun section

### ISSUE THREAD

**Issue by aryanpandey1507** [ghulamyazdani/TruHealth#61]
This section can include motivational quotes too.

**Comment by aryanpandey1507** [comment]
I can add a whole new joke and fun section here , Fetching the jokes from Api and some more fun feature

**Comment by aryanpandey1507** [comment]
Kindly assign me this issue

**Comment by ghulamyazdani** [comment]
Cool go ahead and make a PR for it

**Comment by aryanpandey1507** [comment]
kindly let me know if there is anything more to add
