### ISSUE TITLE
Fixing And Restyling The Fun Section

### ISSUE THREAD

**Issue by snahashisk** [ghulamyazdani/TruHealth#69]
![funDesign](https://user-images.githubusercontent.com/77480125/146320491-957bec32-df10-41eb-aa6b-d8cab019af3e.png)

I can implement this design. And I'll be adding **copy to clipboard** functionality to it to share jokes or quotes. 

![Inkedfun_issue_1_LI](https://user-images.githubusercontent.com/77480125/146320646-02686238-89dd-47da-8845-640494638681.jpg)

Sometimes the generate joke function gives an **undefined value** I'll be fixing this.

![fun_issue_2](https://user-images.githubusercontent.com/77480125/146320775-2966d523-8f90-4223-be71-7133f4ff9947.jpg)

The games section is **not visible** in the navbar I'll fix this too.
Please assign me this @ghulamyazdani

**Comment by aryanpandey1507** [comment]
cool  designs of the fun section

**Comment by snahashisk** [comment]
I have created a pr @ghulamyazdani  @akshatnema
