### ISSUE TITLE
Fixing the footer position

### ISSUE THREAD

**Issue by snahashisk** [ghulamyazdani/TruHealth#73]
![footer-issue01](https://user-images.githubusercontent.com/77480125/146573440-bc0aa2aa-de7e-4548-858d-d30f3a8fd767.JPG)
![footer-issue02](https://user-images.githubusercontent.com/77480125/146573446-98d755fd-9437-44e3-a19b-b284fa723f85.JPG)

Footer is showing in the **middle** of the page in some sections I think it's **breaking our UI**. 
I can fix this and can redesign it a bit.
I can make the UI a little bit **mobile-friendly**.
Please assign me this @ghulamyazdani @akshatnema

**Comment by MukulsinghRajpurohit** [comment]
hi I know how to fix it can some one assigned me it will my 1 major contribution to project

**Comment by Shlok1999** [comment]
Hi, I would like to fix this issue, please asssign me the project
