### ISSUE TITLE
Create a responsive web app for every device and user

### ISSUE THREAD

**Issue by Harsha200105** [ghulamyazdani/TruHealth#8]
Can I work on the UX of TruHealth

**Comment by ghulamyazdani** [comment]
I would be great @Harsha200105 !!! Go on...

Here are some resources to follow along!
#### Resources 🧾 
- [Figma Link](https://www.figma.com/file/ffaR99qwXVsQBJQL7gjlZA/TruHealth?node-id=0%3A1)
- [Doc Link](https://docs.google.com/document/d/1g_S4Vlf6fgDXb0Esvq5mP_6whN0C9sHi0znJAQ9_Fxg/edit?usp=sharing)
- [Presentation](https://docs.google.com/document/d/1g_S4Vlf6fgDXb0Esvq5mP_6whN0C9sHi0znJAQ9_Fxg/edit?usp=sharing)

**Comment by m3gh4l4** [comment]
The design is looking cool. I could do one of the four pages that you kept in the nav bar. Making the whole thing would be a bit heavy.

**Comment by yashfalke77** [comment]
Is it  still open ?

**Comment by m3gh4l4** [comment]
yeah :)
