### ISSUE TITLE
News section in TruHealth 

### ISSUE THREAD

**Issue by MayankRaje** [ghulamyazdani/TruHealth#82]
Sir we can create a news section for users  though which we can attract many users to our platform and as we know many people feel healthier by reading news.
sir please assign this issue to me

**Comment by ghulamyazdani** [comment]
Adding news to a mental health website wont make any sense ,Yeah we can add some more information about mental health .

**Comment by MayankRaje** [comment]
ok sir i have created an another issue plz have a look on it
