### ISSUE TITLE
Fixing the Audio Player Section

### ISSUE THREAD

**Issue by snahashisk** [ghulamyazdani/TruHealth#91]
The design aesthetic of this section isn't going with the rest of the page. I'll be fixing this. Add navbar to this section. And I'll be making this section mobile responsive. 
Please assign me this @ghulamyazdani .

**Comment by ghulamyazdani** [comment]
Adding one more thing here ! We don't need the Audio player listed on the navbar it's going out of context. Can you please remove it from there and add it somewhere it would fit, Like in the Games card section.
One suggestion we can change the name of the games section to Fun and add an Audio player there.
